version: '3'
services:
  discovery-server:
    build: discovery-server
    container_name: discovery-server
    restart: always
    ports:
      - 8761:8761
    networks: 
      - localhost
  ratings-data-service:
    build: ratings-data-service
    container_name: ratings-data-service
    depends_on: 
      - discovery-server
    restart: always
    ports:
      - 8083:8083
    networks: 
      - localhost
networks: 
  localhost: {}